<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo" failures="1" tests="4" name="retry" time="0.05" errors="0" timestamp="2025-01-26T23:27:42 IST">
  <testcase classname="testNG.RetryTest" name="retryTest" time="0.01">
    <skipped/>
  </testcase> <!-- retryTest -->
  <testcase classname="testNG.RetryTest" name="retryTest" time="0.001">
    <skipped/>
  </testcase> <!-- retryTest -->
  <testcase classname="testNG.RetryTest" name="retryTest" time="0.001">
    <skipped/>
  </testcase> <!-- retryTest -->
  <testcase classname="testNG.RetryTest" name="retryTest" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNG.RetryTest.retryTest(RetryTest.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- retryTest -->
</testsuite> <!-- retry -->
